### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by sulaimanbale** [olafhartong/ThreatHunting#38]
Hi, 
Using the latest splunk, i am stuck here.

![image](https://user-images.githubusercontent.com/46603663/65942029-01848980-e45f-11e9-8a3a-b97726c10efe.png)

What to do now ?

**Comment by sulaimanbale** [comment]
Can someone help me to get this working ?

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65943304-b9b33180-e461-11e9-95e5-e5a3580ac7a4.png)

No forwarders 


Sysmon already set up

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65943578-5e357380-e462-11e9-9af5-c63fc378fc69.png)


Please take a look

**Comment by sulaimanbale11** [comment]
Unable to download link analysis app.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/65950172-1f0e1f00-e470-11e9-8ea2-a0395cf6b413.png)

No forwarders to select for data input.

**Comment by Kirtar22** [comment]
@sulaimanbale  - After Clicking "Data Inputs" ; 
- Select the "Microsoft-Sysmon-Operational"  from "available logs"; then
- Select "windows" index from the dropdown ( you need to create the index named "windows" before you perform this step, as stated in one of my comments)  
- complete the wizard. 

The rest of the sub-steps( of Step:4) are not required for newer version of ThreatHunting App as these are taken care by @olafhartong .

I hope this helps.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/66094060-2b57c080-e5c5-11e9-9bba-0b9161dc8805.png)


Hi i am unable to see Select the "Microsoft-Sysmon-Operational" from "available logs" under "Local event log collection"

**Comment by billmurrin** [comment]
Hi @sulaimanbale, I will try to help you. Have you installed the Universal forwarder on your system and are you sending your sysmon logs to your Splunk instance?

For example. in your universal forwarder, copy your `inputs.conf` from `INSTALL LOCATION\SplunkUniversalForwarder\etc\system\default` into the `INSTALL LOCATION\SplunkUniversalForwarder\etc\system\local` and edit it, adding the following lines to it

```
### Sysmon Logs ###
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index=sysmon
disabled = false
renderXml = true
```

After that, you can restart your Universal Forwarder and it should be forwarding the logs.

The next thing is to insure you are receiving data on that port (might be 9997 by default). In Splunk, go to `Settings -> Forwarding and Receiving -> Receiving` ensure that your receiving port is enabled.

I would also consider downloading the Splunk Sysmon Technical Add-on so that the data is parsed using the Common Information Model (CIM) when it is ingested.

**Comment by sulaimanbale11** [comment]
Hi, yes sysmon is up and working and after that I'm stuck at this steop for data input. Hope you can help me.

**Comment by billmurrin** [comment]
Is the Splunk universal forwarder installed on your system?

**Comment by sulaimanbale** [comment]
Yes it is installed.

**Comment by sulaimanbale** [comment]
Is there any way i can contact you personally ?

**Comment by billmurrin** [comment]
Have you configured Sysmon logs to be forwarded in the inputs.conf like I listed above? And did you enable the receiving of data on port 9997 (default)? After it is enabled, you should restart Splunk.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/67612402-eb0aed00-f7d4-11e9-9c8d-d12c7f162cba.png)

Yes done !

**Comment by sulaimanbale** [comment]
Please let me know what to do next.

**Comment by billmurrin** [comment]
It looks like your sysmon data is getting ingested. Do you see anything getting ingested in the ThreatHunting (TH) Application? If not, go into your TH App macros (Settings->Advanced Search->Macros) and ensure you update the `sysmon` macro with the proper source/sourcetype. That will ensure that the saved searches execute properly.

**Comment by sulaimanbale** [comment]
![image](https://user-images.githubusercontent.com/46603663/67733902-8d77da00-fa3a-11e9-9823-eb2700409556.png)

Is it right ?

**Comment by billmurrin** [comment]
Are your sysmon logs in the windows index?

**Comment by sulaimanbale** [comment]
yes , i believe.

**Comment by billmurrin** [comment]
did you create your threathunting index?

**Comment by mlinton** [comment]
Hi @billmurrin, I am also having some difficulty getting the indexing working properly.

I'm using the latest Splunk Enterprise (8).  I have got my SplunkUniversalForwarder properly forwarding events from the test desktop to the splunk server.  I originally didn't have the index = sysmon in the inputs.conf of the forwarder.

I can see events being ingested in the sysmon index.

![image](https://user-images.githubusercontent.com/2158650/69467097-d5410700-0d43-11ea-8e8a-e731c2868f4a.png)

However inside the threathunting app trigger overview I see all zeros:

![image](https://user-images.githubusercontent.com/2158650/69467133-face1080-0d43-11ea-9e77-51cdff653a97.png)

I'm also not sure what the "ThreatHunting App Index" is referring to???

Thanks.

**Comment by sulaimanbale** [comment]
Hi, still stuck kindly help with a detailed guide if possible.

**Comment by billmurrin** [comment]
@mlinton - you have to create the threathunting index so that the data from the sysmon index is stored in that summary index which drives the app's dashboards. The threathunting summary index is populated via saved searches that are part of the app.

@sulaimanbale - I am sorry to hear that you are still have issues. I will see what other things I can come up with to help you out.

**Comment by zhjygit** [comment]
@billmurrin
Hi sir,
What I have done is as follows:
splunk server:win 10, 9.1 version, 192.168.80.1
target pc: win 10, sysmon 15.0version, SplunkUniversalForwarder installed.
       sysmon64.exe -accepteula -i sysmonconfig.xml     this xml is from [https://github.com/olafhartong/sysmon-modular/blob/master/sysmonconfig.xml](https://link.segmentfault.com/?enc=oGwxyEPLUHRds3a2B0DAiA==.0/xbWgmprm1Lo/o4/uKeZoiwlU5k+I+HsG1f6YJLo+sMrbS5ZH5y1kgbTPgbkFHKLy/g+2vqaN2sU9eL9weItc+40M7s6teuHG3hjYi6oS8=)
      C:\Program Files\SplunkUniversalForwarder\etc\apps\SplunkUniversalForwarder\default\inputs.conf is as follows:
              [WinEventLog://Microsoft-Windows-Sysmon/Operational]
              disabled = false
              renderXml = false
              index = windows
              source = WinEventLog:Microsoft-Windows-Sysmon/Operational
       Target PC has nothing  else changed.

Splunk server is as follows:
    install threathunting app;install add-on except "Splunk Add-on for Sysmon"
  downloading and install .csv files.
  add windows and threathunting indexes to Threathunting apps;
  http://127.0.0.1:8000/zh-CN/manager/ThreatHunting/deployment/server/setup/data/inputs/remote_eventlogs:added all of 5 logs

  And then, on dashboard of  http://127.0.0.1:8000/zh-CN/manager/ThreatHunting/data/indexes#, I can see data of index=windows.
  However, no data in index of threathunging from index=window. In fact, I cannot understand that, there are some logs of index=threathunging,  which are about log of splunk server PC  instead of target PC (so shit...)
![image](https://github.com/olafhartong/ThreatHunting/assets/44870751/06971eb4-578f-486a-a03e-0153f9080df1)
![image](https://github.com/olafhartong/ThreatHunting/assets/44870751/9a28486b-d671-45fc-ac30-2e59c1f141b1)

As above shown, index=threathunting, host is splunk server itself, not target PC.


At last, no data index=threathunting from windows, no data or activity on dashboard of http://127.0.0.1:8000/zh-CN/app/ThreatHunting/threat_hunting_overview.

The macro of sysmon is  as follows:
![image](https://github.com/olafhartong/ThreatHunting/assets/44870751/548eba99-065d-4da8-9943-2bef7f9280aa)
